# Generated by Django 3.0.5 on 2021-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=255)),
                ('movie_title', models.CharField(max_length=255)),
                ('video_type', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('country_origin', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
    ]
