# Generated by Django 3.0.5 on 2021-04-19 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(default='5cQdbKoPpbqAH9mFti4vTK', editable=False, max_length=255)),
                ('movie_title', models.CharField(max_length=255)),
                ('video_type', models.CharField(choices=[('YT', 'YouTube'), ('FB', 'Facebook'), ('OK', 'Одноклассники'), ('DM', 'Dailymotion'), ('VM', 'Vimeo')], default=1, max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('country_origin', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('published_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
